add prepare_env and call it in fireboot

diff --git a/bin/fireboot b/bin/fireboot
--- a/bin/fireboot
+++ b/bin/fireboot
@@ -5,6 +5,14 @@ _rc=0
 # step 1 - apply network config
 echo "Applying last successful network config..."
 
+HTTP_STATUS_CODE=`curl -s -o /dev/null -w "%{http_code}" 'http://localhost:8837/v1/config/prepare_env' -XPOST -H 'Content-Type: application/json' -d {}`
+if [[ $HTTP_STATUS_CODE != "200" ]]; then
+  echo "Failed to prepare environment"
+  _rc=3
+fi
+
+test $_rc -eq  0 || exit $_rc
+
 HTTP_STATUS_CODE=`curl -s -o /dev/null -w "%{http_code}" 'http://localhost:8837/v1/config/apply_current_config' -XPOST -H 'Content-Type: application/json' -d {}`
 if [[ $HTTP_STATUS_CODE != "200" ]]; then
   echo "Failed to apply current config"
